In [11]:
# 22 варіант

!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np
# Отримання версії бібліотеки NumPy
numpy_version = np.__version__
print(f"NumPy version: {numpy_version}")

NumPy version: 2.0.1


In [7]:
#Завдання 1
'''
Створіть одновимірний масив (вектор) зі значеннями 𝑒^𝑥 для кожного 
натурального числа x, починаючи з 1, та виведіть його значення.
'''
# Визначимо діапазон натуральних чисел (наприклад, від 1 до 10)
x_values = np.arange(1, 11)

# Обчислимо значення e^x для кожного x
exp_values = np.exp(x_values)

# Виведемо результуючий масив
print("Масив значень e^x для x від 1 до 10:", exp_values)

Масив значень e^x для x від 1 до 10: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [6]:
#Завдання 2
'''
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його тангенсами 
кожного натурального числа, починаючи з 1, та виведіть його значення.
'''
# Визначимо діапазон натуральних чисел (від 1 до 9)
x_values = np.arange(1, 10)

# Обчислимо тангенси для кожного значення
tan_values = np.tan(x_values)

# Створимо двовимірний масив 3x3 і заповнимо його тангенсами
matrix = tan_values.reshape(3, 3)

# Виведемо результуючу матрицю
print("Матриця 3x3, заповнена тангенсами натуральних чисел від 1 до 9:")
print(matrix)

Матриця 3x3, заповнена тангенсами натуральних чисел від 1 до 9:
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [8]:
#Завдання 3
'''
Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до
1 та виведіть непарні числа.
'''
# Створюємо масив розміром 3x3 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (3, 3))

# Виводимо початкову матрицю
print("Матриця 3x3 з випадковими числами від -1 до 1:")
print(matrix)

# Перевіряємо, які елементи матриці є непарними
# Спочатку округлимо до цілих та залишимо лише непарні числа
odd_numbers = matrix[np.round(matrix).astype(int) % 2 != 0]

# Виводимо непарні числа
print("Непарні числа в матриці:")
print(odd_numbers)

Матриця 3x3 з випадковими числами від -1 до 1:
[[ 0.63751013  0.142977    0.10199529]
 [-0.64197701  0.80757511 -0.9427671 ]
 [-0.80709451  0.44394377 -0.64621487]]
Непарні числа в матриці:
[ 0.63751013 -0.64197701  0.80757511 -0.9427671  -0.80709451 -0.64621487]


In [9]:
#Завдання 4
'''
Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.8
до 0.8 та виведіть його значення.
'''
# Створюємо масив розміром 4x4 з випадковими дійсними числами від -0.8 до 0.8
matrix = np.random.uniform(-0.8, 0.8, (4, 4))

# Виводимо результуючий масив
print("Матриця 4x4 з випадковими числами від -0.8 до 0.8:")
print(matrix)

Матриця 4x4 з випадковими числами від -0.8 до 0.8:
[[ 0.14250588 -0.68361265  0.44143487  0.42112563]
 [-0.1848988   0.69902894  0.67760427 -0.00283607]
 [-0.13981104 -0.6303929   0.07501833  0.30757542]
 [ 0.20180668  0.69748034 -0.69200096 -0.78214651]]


In [10]:
#Завдання 5
'''
Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими
числами в діапазоні від 5 до 15 та виконайте на них поелементні операції додавання,
віднімання та множення.
'''
# Створюємо два одновимірних масиви розміром 6 з випадковими цілими числами від 5 до 15
array1 = np.random.randint(5, 16, 6)
array2 = np.random.randint(5, 16, 6)

# Виконуємо поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виводимо результати
print("Перший масив:", array1)
print("Другий масив:", array2)
print("Поелементне додавання:", addition)
print("Поелементне віднімання:", subtraction)
print("Поелементне множення:", multiplication)

Перший масив: [ 6 15 14 15 12  7]
Другий масив: [15 10  9 11 10 14]
Поелементне додавання: [21 25 23 26 22 21]
Поелементне віднімання: [-9  5  5  4  2 -7]
Поелементне множення: [ 90 150 126 165 120  98]


In [12]:
#Завдання 6
'''
Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -6 до 6 та
знайдіть їх добуток.
'''
# Створюємо дві матриці 4x4 з випадковими цілими числами від -6 до 6
matrix1 = np.random.randint(-6, 7, (4, 4))
matrix2 = np.random.randint(-6, 7, (4, 4))

# Знаходимо добуток матриць
product = np.dot(matrix1, matrix2)

# Виводимо результати
print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nДобуток матриць:")
print(product)


Перша матриця:
[[ 2 -2  4  1]
 [-5  2 -4 -5]
 [-4  3  6 -1]
 [-6  6 -3  0]]

Друга матриця:
[[-2  4 -6 -5]
 [-3  3 -6 -1]
 [ 4 -4  4 -5]
 [-4 -5  0  6]]

Добуток матриць:
[[ 14 -19  16 -22]
 [  8  27   2  13]
 [ 27 -26  30 -19]
 [-18   6 -12  39]]


In [13]:
#Завдання 7
'''
Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 8 та перемножте їх між собою.
'''
# Створюємо першу матрицю розміром 3x2 з випадковими цілими числами від 1 до 8
matrix1 = np.random.randint(1, 9, (3, 2))

# Створюємо другу матрицю розміром 2x2 з випадковими цілими числами від 1 до 8
matrix2 = np.random.randint(1, 9, (2, 2))

# Перемножуємо матриці
product = np.dot(matrix1, matrix2)

# Виводимо результати
print("Перша матриця (3x2):")
print(matrix1)
print("\nДруга матриця (2x2):")
print(matrix2)
print("\nДобуток матриць (3x2 * 2x2):")
print(product)

Перша матриця (3x2):
[[2 1]
 [8 2]
 [5 1]]

Друга матриця (2x2):
[[1 4]
 [2 8]]

Добуток матриць (3x2 * 2x2):
[[ 4 16]
 [12 48]
 [ 7 28]]


In [14]:
#Завдання 8
'''
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 8 та знайдіть її обернену матрицю.
'''
# Створюємо матрицю розміром 3x3 з випадковими цілими числами від 1 до 8
matrix = np.random.randint(1, 9, (3, 3))

# Знаходимо обернену матрицю
inverse_matrix = np.linalg.inv(matrix)

# Виводимо результати
print("Початкова матриця (3x3):")
print(matrix)
print("\nОбернена матриця:")
print(inverse_matrix)

Початкова матриця (3x3):
[[5 8 4]
 [8 7 4]
 [2 2 2]]

Обернена матриця:
[[-0.23076923  0.30769231 -0.15384615]
 [ 0.30769231 -0.07692308 -0.46153846]
 [-0.07692308 -0.23076923  1.11538462]]


In [15]:
#Завдання 9
'''
Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та транспонуйте її.
'''
# Створюємо матрицю розміром 4x4 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (4, 4))

# Транспонуємо матрицю
transposed_matrix = matrix.T

# Виводимо результати
print("Початкова матриця (4x4):")
print(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця (4x4):
[[ 0.68494379 -0.20094702 -0.43395578 -0.94442522]
 [-0.75232994 -0.13095603 -0.17763535  0.74626592]
 [-0.91014386 -0.39397177 -0.33986988 -0.68517783]
 [ 0.58827166  0.63376663 -0.65606038  0.78238662]]

Транспонована матриця:
[[ 0.68494379 -0.75232994 -0.91014386  0.58827166]
 [-0.20094702 -0.13095603 -0.39397177  0.63376663]
 [-0.43395578 -0.17763535 -0.33986988 -0.65606038]
 [-0.94442522  0.74626592 -0.68517783  0.78238662]]


In [16]:
#Завдання 10
'''
Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
'''
# Створюємо матрицю розміром 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, (3, 4))

# Створюємо вектор розміром 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, (4, 1))

# Знаходимо добуток матриці на вектор
result = np.dot(matrix, vector)

# Виводимо результати
print("Матриця (3x4):")
print(matrix)
print("\nВектор (4x1):")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця (3x4):
[[0.12081269 0.12645875 0.97800749 0.68688842]
 [0.52238182 0.60635196 0.90955343 0.01668644]
 [0.16219875 0.23598834 0.2941479  0.20475929]]

Вектор (4x1):
[[7]
 [4]
 [2]
 [9]]

Добуток матриці на вектор:
[[9.48953459]
 [8.05136535]
 [4.51047404]]


In [17]:
#Завдання 11
'''
Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.
'''
# Створюємо матрицю розміром 2x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (2, 3))

# Створюємо вектор розміром 3 з випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, 3)

# Знаходимо добуток матриці на вектор
result = np.dot(matrix, vector)

# Виводимо результати
print("Матриця (2x3):")
print(matrix)
print("\nВектор (3):")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця (2x3):
[[9 6 3]
 [2 8 6]]

Вектор (3):
[0.52997263 0.10995473 0.5693555 ]

Добуток матриці на вектор:
[7.13754859 5.35571613]


In [18]:
#Завдання 12
'''
Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 3 та знайдіть суму всіх елементів другої матриці.
'''
# Створюємо дві матриці розміром 3x3 з випадковими цілими числами від 1 до 3
matrix1 = np.random.randint(1, 4, (3, 3))
matrix2 = np.random.randint(1, 4, (3, 3))

# Знаходимо суму всіх елементів другої матриці
sum_matrix2 = np.sum(matrix2)

# Виводимо результати
print("Перша матриця (3x3):")
print(matrix1)
print("\nДруга матриця (3x3):")
print(matrix2)
print("\nСума всіх елементів другої матриці:")
print(sum_matrix2)

Перша матриця (3x3):
[[2 1 3]
 [2 3 3]
 [3 2 1]]

Друга матриця (3x3):
[[3 2 3]
 [3 3 1]
 [3 3 3]]

Сума всіх елементів другої матриці:
24


In [19]:
#Завдання 13
'''
Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть суму їх елементів.
'''
# Створюємо дві матриці розміром 3x3 з випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))

# Знаходимо суму всіх елементів першої та другої матриці
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

# Виводимо результати
print("Перша матриця (3x3):")
print(matrix1)
print("\nСума елементів першої матриці:")
print(sum_matrix1)

print("\nДруга матриця (3x3):")
print(matrix2)
print("\nСума елементів другої матриці:")
print(sum_matrix2)

# Загальна сума елементів обох матриць
total_sum = sum_matrix1 + sum_matrix2
print("\nЗагальна сума елементів обох матриць:")
print(total_sum)

Перша матриця (3x3):
[[3 2 1]
 [3 5 4]
 [2 2 5]]

Сума елементів першої матриці:
27

Друга матриця (3x3):
[[4 4 1]
 [1 2 1]
 [1 1 1]]

Сума елементів другої матриці:
16

Загальна сума елементів обох матриць:
43


In [22]:
#Завдання 14
'''
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть суму елементів на головній діагоналі.
'''
# Створюємо матрицю розміром 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Знаходимо суму елементів на головній діагоналі
sum_diagonal = np.trace(matrix)

# Виводимо результати
print("Матриця (3x3):")
print(matrix)
print("\nСума елементів на головній діагоналі:")
print(sum_diagonal)

Матриця (3x3):
[[8 5 2]
 [2 3 3]
 [3 2 2]]

Сума елементів на головній діагоналі:
13


In [24]:
#Завдання 15
'''
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів
кожного стовпця матриці.
'''
# Створюємо матрицю розміром 3x3 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (3, 3))

# Знаходимо добуток елементів кожного стовпця
column_products = np.prod(matrix, axis=0)

# Перетворюємо результати в вектор-стовпчик
column_vector = column_products.reshape(-1, 1)

# Виводимо результати
print("Матриця (3x3):")
print(matrix)
print("\nВектор-стовпчик з добутком елементів кожного стовпця:")
print(column_vector)

Матриця (3x3):
[[ 0.89253364 -0.47313178 -0.39254974]
 [-0.38488866  0.52270697  0.59296307]
 [-0.85154763 -0.5711649  -0.11793439]]

Вектор-стовпчик з добутком елементів кожного стовпця:
[[0.29252882]
 [0.14125438]
 [0.02745129]]


In [27]:
'''
Було створено різні масиви і матриці, заповнені випадковими числами. 
Виконано поелементні операції додавання, віднімання, множення.
Обчислено добуток матриць і векторів. 
Транспоновано матрицю, знайдено обернену матрицю, а також суму елементів на головній діагоналі. 
Весь процес допоміг закріпити розуміння роботи з NumPy та основними операціями над масивами.
'''

'\nБуло створено різні масиви і матриці, заповнені випадковими числами. \nВиконано поелементні операції додавання, віднімання, множення.\nОбчислено добуток матриць і векторів. \nТранспоновано матрицю, знайдено обернену матрицю, а також суму елементів на головній діагоналі. \nВесь процес допоміг закріпити розуміння роботи з NumPy та основними операціями над масивами.\n'